version: '3'
services:
  database:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres # required
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d # mount volume with init scripts
    ports:
      - "5432:5432"